package com.usermanagement.service;

import com.usermanagement.domain.Department;
import com.usermanagement.domain.DepartmentStatus;
import com.usermanagement.repository.DepartmentRepository;
import com.usermanagement.web.dto.DepartmentCreateRequest;
import com.usermanagement.web.dto.DepartmentDTO;
import com.usermanagement.web.dto.DepartmentTreeResponse;
import com.usermanagement.web.dto.DepartmentUpdateRequest;
import com.usermanagement.web.mapper.DepartmentMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.BDDMockito.given;
import static org.mockito.BDDMockito.then;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

/**
 * DepartmentService 单元测试
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("DepartmentService 测试")
class DepartmentServiceTest {

    @Mock
    private DepartmentRepository departmentRepository;

    @Mock
    private DepartmentMapper departmentMapper;

    @Mock
    private TreeBuilder<Department> treeBuilder;

    private DepartmentServiceImpl departmentService;

    private static final String TEST_DEPT_NAME = "技术部";
    private static final String TEST_DEPT_CODE = "TECH";
    private static final UUID TEST_DEPT_ID = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
    private static final UUID TEST_PARENT_ID = UUID.fromString("660e8400-e29b-41d4-a716-446655440001");
    private static final UUID TEST_MANAGER_ID = UUID.fromString("770e8400-e29b-41d4-a716-446655440002");

    @BeforeEach
    void setUp() {
        departmentService = new DepartmentServiceImpl(departmentRepository, departmentMapper, treeBuilder);
    }

    @Nested
    @DisplayName("创建部门测试")
    class CreateDepartmentTests {

        @Test
        @DisplayName("应该创建根部门并自动生成 path")
        void shouldCreateRootDepartmentWithAutoGeneratedPath() {
            // Given
            DepartmentCreateRequest request = new DepartmentCreateRequest();
            request.setName(TEST_DEPT_NAME);
            request.setCode(TEST_DEPT_CODE);
            request.setLevel(1);

            Department department = createDepartment(1, null);
            DepartmentDTO dto = createDTO("ACTIVE");

            given(departmentRepository.existsByCode(TEST_DEPT_CODE)).willReturn(false);
            given(departmentMapper.toEntity(request)).willReturn(department);
            given(departmentRepository.save(department)).willReturn(department);
            given(departmentMapper.toDto(department)).willReturn(dto);

            // When
            DepartmentDTO result = departmentService.createDepartment(request);

            // Then
            assertThat(result).isNotNull();
            assertThat(result.getId()).isEqualTo(TEST_DEPT_ID.toString());
            assertThat(department.getPath()).isEqualTo("/" + TEST_DEPT_ID);

            ArgumentCaptor<Department> deptCaptor = ArgumentCaptor.forClass(Department.class);
            then(departmentRepository).should().save(deptCaptor.capture());
            Department savedDept = deptCaptor.getValue();
            assertThat(savedDept.getPath()).startsWith("/");
        }

        @Test
        @DisplayName("应该创建子部门并继承父部门 path")
        void shouldCreateChildDepartmentWithInheritedPath() {
            // Given
            DepartmentCreateRequest request = new DepartmentCreateRequest();
            request.setName("子部门");
            request.setCode("CHILD");
            request.setLevel(2);
            request.setParentId(TEST_PARENT_ID.toString());

            Department parent = createDepartment(1, null);
            parent.setId(TEST_PARENT_ID);
            parent.setPath("/parent-path");

            Department child = createDepartment(2, TEST_PARENT_ID);
            DepartmentDTO dto = createDTO("ACTIVE");

            given(departmentRepository.existsByCode("CHILD")).willReturn(false);
            given(departmentRepository.findById(TEST_PARENT_ID)).willReturn(Optional.of(parent));
            given(departmentMapper.toEntity(request)).willReturn(child);
            given(departmentRepository.save(child)).willReturn(child);
            given(departmentMapper.toDto(child)).willReturn(dto);

            // When
            DepartmentDTO result = departmentService.createDepartment(request);

            // Then
            assertThat(result).isNotNull();
            assertThat(child.getPath()).isEqualTo("/parent-path/" + child.getId());
        }

        @Test
        @DisplayName("父部门不存在时抛出异常")
        void shouldThrowExceptionWhenParentNotFound() {
            // Given
            DepartmentCreateRequest request = new DepartmentCreateRequest();
            request.setName("子部门");
            request.setCode("CHILD");
            request.setLevel(2);
            request.setParentId(TEST_PARENT_ID.toString());

            given(departmentRepository.existsByCode("CHILD")).willReturn(false);
            given(departmentRepository.findById(TEST_PARENT_ID)).willReturn(Optional.empty());

            // When & Then
            assertThatThrownBy(() -> departmentService.createDepartment(request))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("父部门不存在");

            verify(departmentRepository, never()).save(any());
        }

        @Test
        @DisplayName("部门代码已存在时抛出异常")
        void shouldThrowExceptionWhenCodeExists() {
            // Given
            DepartmentCreateRequest request = new DepartmentCreateRequest();
            request.setName(TEST_DEPT_NAME);
            request.setCode(TEST_DEPT_CODE);
            request.setLevel(1);

            given(departmentRepository.existsByCode(TEST_DEPT_CODE)).willReturn(true);

            // When & Then
            assertThatThrownBy(() -> departmentService.createDepartment(request))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("部门代码已存在");

            verify(departmentRepository, never()).save(any());
        }

        @Test
        @DisplayName("应该设置部门负责人")
        void shouldSetDepartmentManager() {
            // Given
            DepartmentCreateRequest request = new DepartmentCreateRequest();
            request.setName(TEST_DEPT_NAME);
            request.setCode(TEST_DEPT_CODE);
            request.setLevel(1);
            request.setManagerId(TEST_MANAGER_ID.toString());

            Department department = createDepartment(1, null);
            DepartmentDTO dto = createDTO("ACTIVE");

            given(departmentRepository.existsByCode(TEST_DEPT_CODE)).willReturn(false);
            given(departmentMapper.toEntity(request)).willReturn(department);
            given(departmentRepository.save(department)).willReturn(department);
            given(departmentMapper.toDto(department)).willReturn(dto);

            // When
            departmentService.createDepartment(request);

            // Then
            assertThat(department.getManagerId()).isEqualTo(TEST_MANAGER_ID);
        }
    }

    @Nested
    @DisplayName("更新部门测试")
    class UpdateDepartmentTests {

        @Test
        @DisplayName("应该更新部门信息")
        void shouldUpdateDepartment() {
            // Given
            Department department = createDepartment(1, null);
            DepartmentDTO dto = createDTO("ACTIVE");

            DepartmentUpdateRequest request = new DepartmentUpdateRequest();
            request.setName("新名称");
            request.setDescription("新描述");
            request.setSortOrder(5);

            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.of(department));
            given(departmentMapper.toDto(department)).willReturn(dto);

            // When
            DepartmentDTO result = departmentService.updateDepartment(TEST_DEPT_ID, request);

            // Then
            assertThat(result).isNotNull();
            assertThat(department.getName()).isEqualTo("新名称");
            assertThat(department.getDescription()).isEqualTo("新描述");
            assertThat(department.getSortOrder()).isEqualTo(5);
            verify(departmentRepository).save(department);
        }

        @Test
        @DisplayName("应该更新部门负责人")
        void shouldUpdateDepartmentManager() {
            // Given
            Department department = createDepartment(1, null);
            DepartmentDTO dto = createDTO("ACTIVE");

            DepartmentUpdateRequest request = new DepartmentUpdateRequest();
            request.setManagerId(TEST_MANAGER_ID.toString());

            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.of(department));
            given(departmentMapper.toDto(department)).willReturn(dto);

            // When
            departmentService.updateDepartment(TEST_DEPT_ID, request);

            // Then
            assertThat(department.getManagerId()).isEqualTo(TEST_MANAGER_ID);
        }

        @Test
        @DisplayName("部门不存在时抛出异常")
        void shouldThrowExceptionWhenDepartmentNotFound() {
            // Given
            DepartmentUpdateRequest request = new DepartmentUpdateRequest();
            request.setName("新名称");

            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.empty());

            // When & Then
            assertThatThrownBy(() -> departmentService.updateDepartment(TEST_DEPT_ID, request))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("部门不存在");
        }

        @Test
        @DisplayName("不应该修改部门代码")
        void shouldNotModifyDepartmentCode() {
            // Given
            Department department = createDepartment(1, null);
            String originalCode = department.getCode();

            DepartmentUpdateRequest request = new DepartmentUpdateRequest();
            request.setName("新名称");

            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.of(department));
            given(departmentMapper.toDto(department)).willReturn(createDTO("ACTIVE"));

            // When
            departmentService.updateDepartment(TEST_DEPT_ID, request);

            // Then
            assertThat(department.getCode()).isEqualTo(originalCode);
        }
    }

    @Nested
    @DisplayName("查询部门测试")
    class GetDepartmentTests {

        @Test
        @DisplayName("应该根据 ID 获取部门")
        void shouldGetDepartmentById() {
            // Given
            Department department = createDepartment(1, null);
            DepartmentDTO dto = createDTO("ACTIVE");

            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.of(department));
            given(departmentMapper.toDto(department)).willReturn(dto);

            // When
            DepartmentDTO result = departmentService.getDepartmentById(TEST_DEPT_ID);

            // Then
            assertThat(result).isNotNull();
            assertThat(result.getId()).isEqualTo(TEST_DEPT_ID.toString());
        }

        @Test
        @DisplayName("部门不存在时抛出异常")
        void shouldThrowExceptionWhenDepartmentNotFound() {
            // Given
            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.empty());

            // When & Then
            assertThatThrownBy(() -> departmentService.getDepartmentById(TEST_DEPT_ID))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("部门不存在");
        }
    }

    @Nested
    @DisplayName("查询部门树测试")
    class GetDepartmentTreeTests {

        @Test
        @DisplayName("应该获取完整部门树")
        void shouldGetFullDepartmentTree() {
            // Given
            Department root = createDepartment(1, null);
            Department child = createDepartment(2, TEST_DEPT_ID);
            List<Department> departments = List.of(root, child);

            DepartmentDTO rootDto = createDTO("ACTIVE");
            DepartmentDTO childDto = createDTO("ACTIVE");

            given(departmentRepository.findAllOrderedByPath()).willReturn(departments);
            given(treeBuilder.buildTree(departments, null)).willReturn(List.of(root));
            given(departmentMapper.toDto(root)).willReturn(rootDto);
            given(departmentMapper.toDto(child)).willReturn(childDto);

            // When
            DepartmentTreeResponse response = departmentService.getDepartmentTree(null);

            // Then
            assertThat(response).isNotNull();
            assertThat(response.getTree()).isNotEmpty();
        }

        @Test
        @DisplayName("应该支持按层级筛选")
        void shouldFilterByLevel() {
            // Given
            Department root = createDepartment(1, null);
            List<Department> departments = List.of(root);

            DepartmentDTO rootDto = createDTO("ACTIVE");

            given(departmentRepository.findAllOrderedByPath()).willReturn(departments);
            given(treeBuilder.buildTree(departments, 1)).willReturn(List.of(root));
            given(departmentMapper.toDto(root)).willReturn(rootDto);

            // When
            DepartmentTreeResponse response = departmentService.getDepartmentTree(1);

            // Then
            assertThat(response).isNotNull();
            verify(treeBuilder).buildTree(departments, 1);
        }
    }

    @Nested
    @DisplayName("删除部门测试")
    class DeleteDepartmentTests {

        @Test
        @DisplayName("应该软删除部门")
        void shouldSoftDeleteDepartment() {
            // Given
            Department department = createDepartment(1, null);

            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.of(department));

            // When
            departmentService.deleteDepartment(TEST_DEPT_ID);

            // Then
            verify(departmentRepository).delete(department);
            assertThat(department.getDeletedAt()).isNotNull();
        }

        @Test
        @DisplayName("部门不存在时抛出异常")
        void shouldThrowExceptionWhenDepartmentNotFoundForDelete() {
            // Given
            given(departmentRepository.findById(TEST_DEPT_ID)).willReturn(Optional.empty());

            // When & Then
            assertThatThrownBy(() -> departmentService.deleteDepartment(TEST_DEPT_ID))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("部门不存在");
        }
    }

    @Nested
    @DisplayName("检查子部门测试")
    class CheckChildrenTests {

        @Test
        @DisplayName("应该检查部门是否有子部门")
        void shouldCheckDepartmentHasChildren() {
            // Given
            given(departmentRepository.findByParentId(TEST_DEPT_ID)).willReturn(List.of(new Department()));

            // When
            boolean hasChildren = departmentService.hasChildren(TEST_DEPT_ID);

            // Then
            assertThat(hasChildren).isTrue();
        }

        @Test
        @DisplayName("部门没有子部门时返回 false")
        void shouldReturnFalseWhenNoChildren() {
            // Given
            given(departmentRepository.findByParentId(TEST_DEPT_ID)).willReturn(List.of());

            // When
            boolean hasChildren = departmentService.hasChildren(TEST_DEPT_ID);

            // Then
            assertThat(hasChildren).isFalse();
        }
    }

    // 辅助方法
    private Department createDepartment(int level, UUID parentId) {
        Department dept = new Department();
        dept.setId(TEST_DEPT_ID);
        dept.setName(TEST_DEPT_NAME);
        dept.setCode(TEST_DEPT_CODE);
        dept.setLevel(level);
        dept.setParentId(parentId);
        dept.setPath(parentId == null ? "/" + TEST_DEPT_ID : "/parent/" + TEST_DEPT_ID);
        dept.setStatus(DepartmentStatus.ACTIVE);
        return dept;
    }

    private DepartmentDTO createDTO(String status) {
        DepartmentDTO dto = new DepartmentDTO();
        dto.setId(TEST_DEPT_ID.toString());
        dto.setName(TEST_DEPT_NAME);
        dto.setCode(TEST_DEPT_CODE);
        dto.setLevel(1);
        dto.setPath("/" + TEST_DEPT_ID);
        dto.setStatus(status);
        return dto;
    }
}
